language: node_js
node_js:
  - "6"
script:
  - npm run lint
  - npm test
before_install:
  - npm i -g npm@latest
  - npm i -g greenkeeper-lockfile@latest
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
